### ISSUE TITLE
PA Review:  Bookings

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#7]
- [x] Logged in users can _create_ a booking.
- [x] Logged in users can _delete_ a booking they created (cancel booking).
- [ ] Non-Logged in users will be prompted to create an account to proceed with booking.
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ]  Styling
- [ ]  Smooth, bug-free navigation
- [ ]  Adequate and appropriate seeds

**Comment by youknowhu** [comment]
(For my own tracking purpose)
- [x] Logged in users can _create_ a booking.
- [x] Logged in users can _delete_ a booking they created (cancel booking).
- [x] Non-Logged in users will be prompted to create an account to proceed with booking.
- [x] Display errors, if any
- [x] DayPicker Fixes
    - [x] Prevent choosing an end date prior to start date
    - [x] Show selected start or end date when in opposing date field
    - [x] Change calendar date selector to be prettier

**Comment by youknowhu** [comment]
@anastassia-b  this should be ready for review. Functionality should all be there (I think),  going to work on styling the form using intersection observer.

**Comment by anastassia-b** [comment]
Excellent work. The booking is complete in terms of styling and most functionality, there are just a few bugs to address before we mark this MVP as complete. 

- [x] Sometimes the booking doesn't delete properly. Take a look at what id you may be dispatching?
- [x] Sometimes when a booking is made, it redirects to the wrong listing instead of staying on the same page. Probably we don't want to Redirect or push the user anywhere, just have the components on the page re-render.
- [x] There is a bug you noticed when the dev tools are open, that the button to book could not be triggered anymore. Giving the `listing-content` component a z-index of 1 or 2 will bring it up in front of the slider component, allowing a user to always click the buttons.
- [x] Potentially you want to give the `Cancel booking` button to have more of a signifier of deletion? Like a red font maybe.. but this is optional and up to you.
- [x] Give the errors list a padding-top, like your cancel booking.
- [ ] It might be nice to have some default clicked check in and check out dates (for a user testing your site). Also up to you. 
- [x] Booking errors don't clear if I navigate between listings.
- [x] On a smaller screen, the sticky positioning is slightly off (too high). 

We just discussed that the culprit to some of the bugs might be the anti-pattern of setting the props to the state in the constructor of the BookingForm. :)

**Comment by youknowhu** [comment]
@anastassia-b 
- the only thing I am not addressing will be not to have default check in and checkout dates -- I might add them in later, but leaving them off as they added enough complexity to put it as a later item. 
- everything else should be fixed now. I fixed the sticky position by using the DOMRectangle to find the position of the booking form when it is first loaded on the page.

**Comment by anastassia-b** [comment]
Excellent! I love the functionality. I like that I cant pick a checkout date before my checkin date, I like the calculation, and being able to cancel. Can't find any more bugs! This MVP is complete.
